
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnizxrqxvcdvewmwusrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaXp4cnF4dmNkdmV3bXd1c3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzA0OTksImV4cCI6MjA1OTUwNjQ5OX0.e_xHiD-5n49T62_Alz_j3VGELKvqqqaWRRLYxaPcDxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});
